/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product, SellerReview } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'jaket-denim-vintage',
    name: 'Jaket Denim Vintage Classic',
    brand: 'Balenciaga',
    category: 'Atasan',
    size: 'L',
    condition: 'Sangat Baik',
    price: 350000,
    description: 'Jaket denim vintage asli dari era 90-an. Potongan oversized yang sedang tren. Kondisi masih sangat bagus tanpa sobekan major, hanya fading natural pemakaian.',
    imagePrimary: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA7wNUa7UfVaHOj4tcRjHiAPDLJEsJgvVKfcMS_ChAwOr8-SnSP7SVKHcX7epJNB4BwaCu6GFsWDmuvIi6af0cJ682kwunY4gt0mpxc3kC9dM7kbQFf7NOqtPxAW-AOreu6E2XBd5MIINaStAXk1AOsh03RMB1jyhCW4w7M01YB6ZT4Vjb9ARtALwvBB0R9B5OfJKz44ICs-ZsWP3KfZ4jxlJs9bkpzM-Rqjg7-zbn5igPEpGW8OV28ionyrGnYi2l3KdLvzhM_xjeK',
    imageHover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBY7RgKRR--WV_tAd9SPVkiCsi8eLuii-7l7lxX2C8dyEhHpCKjWb5627gWUMBiMbBJsi16MlVBl0KzVr6yM4qOCLIBdSieAwyB11X81dc77fOvUkgUrN-iMr73YacBV7bzavKAV7cxhcmGReVGLaJobEicNTqhnvKiLvs9D9oQu0opEDIxkdX1US33G4Yw887vPTc-tJ-ddZOia8OGA-q0D-p2Bh0Z1sQvHMaVQO5Txo7CyQyUPpuErLVXa9r9mdkZlM330fl152Vx',
    isVerified: true,
    sellerName: 'Studio Vintage JKT',
    sellerRating: 4.9,
    transactions: 120,
    responseTime: '98%',
    stars: 5,
  },
  {
    id: 'leather-boots',
    name: 'Sepatu Boots Kulit',
    brand: 'Common Projects',
    category: 'Sepatu',
    size: '42',
    condition: 'Sangat Baik',
    price: 450000,
    description: 'Minimalist leather boots premium from premium full-grain leather. Very comfortable lining with classic durable stitchdown construction.',
    imagePrimary: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAvoMg3VzgLSzYsclwQT5TJ8egglJgiFkH8AqZADcp_3iAZricvzL6gTbKHy_kOCweg1XQhVfR57X18nrt0BWc--hD4Xiq-18h6_U8hLDqn9W-Uo-R9YvGATAURewIiqNuqKcCMtj47ha4waTap2wPrkjWp6bfN46DYKDQC5pfS4lI8NWaPgxwXCSJGbZ5bq2pGDZyrbZhpWUpr2DS4r4twWIFd7YZy70IfFRWSaayGpFJNQr9trpBuQarv0rFSwt6PSV-ygX4H2zHq',
    imageHover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBY7RgKRR--WV_tAd9SPVkiCsi8eLuii-7l7lxX2C8dyEhHpCKjWb5627gWUMBiMbBJsi16MlVBl0KzVr6yM4qOCLIBdSieAwyB11X81dc77fOvUkgUrN-iMr73YacBV7bzavKAV7cxhcmGReVGLaJobEicNTqhnvKiLvs9D9oQu0opEDIxkdX1US33G4Yw887vPTc-tJ-ddZOia8OGA-q0D-p2Bh0Z1sQvHMaVQO5Txo7CyQyUPpuErLVXa9r9mdkZlM330fl152Vx',
    isVerified: true,
    sellerName: 'UrbanArchive Vintage',
    sellerRating: 4.8,
    transactions: 85,
    responseTime: '95%',
    stars: 4,
  },
  {
    id: 'sweat-wool',
    name: 'Sweater Wool Cream',
    brand: 'EcoStyle',
    category: 'Pakaian Pria',
    size: 'M',
    condition: 'Baik',
    price: 275000,
    description: 'Cozy and heavy loose-knit heavy wool selection. Eco-dyed organic cream hue with relaxed fit shoulder cuts.',
    imagePrimary: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByq6OAT-vWno4PR8k6FHbcNE-0cppxIFOuqCTjxNVnLCc4HoKpiNm6ZJuX3cC8_qVqRiV7lkccvlY2LEUTn9GNORJrU-iXGv2TkOo__EMM5oYXt_OqO1yfdOH--mvMrt_4s7VqeviCUZcF7XG-1OeHvB4mQZBH7yl01S-_zzynWg47yubF_s99wbbzNSj0-hSQAv9ld_BFdej8ok4Eb8nN0r5oiDfaTg-VKchZjqcmFOH24i8Ek0GuAlQiSmS0fOBeOpTE-A0DugbS',
    imageHover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCeaaSSlwZgkNTPgGz4AyxDMt-MWKJdq4PVgkFOUnAOrcFITJyHqtGxxwzq6r-unalJF4MLtNFyUZIaDPx3--QudBhABuXFhOK0Ru2kqtox9GNgL5B3xUhNbyEQ3p9xqhUkIuocopCbiCOF-AOXCE642SL3Av4Vj1Xwm3aZkDFtC_xircD3xswsprnXF0l4NimrpKwjhqDWWLu-IZiu4eE1jJbH7Q0LnZpCQkMBDvbgT0GrtpPjxMIINzxa3eaevmjbWkwOQajCWnlu',
    isVerified: true,
    sellerName: 'Lokal Thrift',
    sellerRating: 4.7,
    transactions: 230,
    responseTime: '92%',
    stars: 4,
  },
  {
    id: 'gaun-musim-panas',
    name: 'Gaun Musim Panas Floral',
    brand: 'Vintage Core',
    category: 'Pakaian Wanita',
    size: 'S',
    condition: 'Baru',
    price: 195000,
    description: 'Lightweight flowing premium summer dress with organic botanical dye details. Side zipper alignment, absolutely like-new condition with tag.',
    imagePrimary: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCeaaSSlwZgkNTPgGz4AyxDMt-MWKJdq4PVgkFOUnAOrcFITJyHqtGxxwzq6r-unalJF4MLtNFyUZIaDPx3--QudBhABuXFhOK0Ru2kqtox9GNgL5B3xUhNbyEQ3p9xqhUkIuocopCbiCOF-AOXCE642SL3Av4Vj1Xwm3aZkDFtC_xircD3xswsprnXF0l4NimrpKwjhqDWWLu-IZiu4eE1jJbH7Q0LnZpCQkMBDvbgT0GrtpPjxMIINzxa3eaevmjbWkwOQajCWnlu',
    imageHover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByq6OAT-vWno4PR8k6FHbcNE-0cppxIFOuqCTjxNVnLCc4HoKpiNm6ZJuX3cC8_qVqRiV7lkccvlY2LEUTn9GNORJrU-iXGv2TkOo__EMM5oYXt_OqO1yfdOH--mvMrt_4s7VqeviCUZcF7XG-1OeHvB4mQZBH7yl01S-_zzynWg47yubF_s99wbbzNSj0-hSQAv9ld_BFdej8ok4Eb8nN0r5oiDfaTg-VKchZjqcmFOH24i8Ek0GuAlQiSmS0fOBeOpTE-A0DugbS',
    isVerified: true,
    sellerName: 'EcoLifestyle JKT',
    sellerRating: 4.9,
    transactions: 140,
    responseTime: '99%',
    stars: 5,
  },
  {
    id: 'canvas-tote',
    name: 'Designer Canvas Tote Bag',
    brand: 'Prada',
    category: 'Aksesoris',
    size: 'One Size',
    condition: 'Sangat Baik',
    price: 1250000,
    description: 'Authentic robust canvas structured shopper bag. Inner multi-pocket setup with premium silk lining and authentication stamp plate.',
    imagePrimary: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCeaaSSlwZgkNTPgGz4AyxDMt-MWKJdq4PVgkFOUnAOrcFITJyHqtGxxwzq6r-unalJF4MLtNFyUZIaDPx3--QudBhABuXFhOK0Ru2kqtox9GNgL5B3xUhNbyEQ3p9xqhUkIuocopCbiCOF-AOXCE642SL3Av4Vj1Xwm3aZkDFtC_xircD3xswsprnXF0l4NimrpKwjhqDWWLu-IZiu4eE1jJbH7Q0LnZpCQkMBDvbgT0GrtpPjxMIINzxa3eaevmjbWkwOQajCWnlu',
    imageHover: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA7wNUa7UfVaHOj4tcRjHiAPDLJEsJgvVKfcMS_ChAwOr8-SnSP7SVKHcX7epJNB4BwaCu6GFsWDmuvIi6af0cJ682kwunY4gt0mpxc3kC9dM7kbQFf7NOqtPxAW-AOreu6E2XBd5MIINaStAXk1AOsh03RMB1jyhCW4w7M01YB6ZT4Vjb9ARtALwvBB0R9B5OfJKz44ICs-ZsWP3KfZ4jxlJs9bkpzM-Rqjg7-zbn5igPEpGW8OV28ionyrGnYi2l3KdLvzhM_xjeK',
    isVerified: true,
    sellerName: 'Studio Vintage JKT',
    sellerRating: 4.9,
    transactions: 154,
    responseTime: '98%',
    stars: 5,
  },
  {
    id: 'vintage-cap',
    name: 'Topi Vintage Retro',
    brand: 'Polo Ralph Lauren',
    category: 'Aksesoris',
    size: 'One Size',
    condition: 'Baik',
    price: 150000,
    description: 'Topi baseball vintage retro Polo Ralph Lauren warna navy fading klasik. Strap kulit di bagian belakang.',
    imagePrimary: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=600',
    imageHover: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=600',
    isVerified: true,
    sellerName: 'Studio Vintage JKT',
    sellerRating: 4.9,
    transactions: 154,
    responseTime: '98%',
    stars: 5,
  }
];

export const INITIAL_REVIEWS: SellerReview[] = [
  {
    id: 'rev-1',
    buyerName: 'Andi Pratama',
    stars: 5,
    text: 'Kualitas jaketnya luar biasa, sesuai deskripsi. Pengiriman sangat cepat dan aman.',
    date: 'Kemarin',
  },
  {
    id: 'rev-2',
    buyerName: 'Siti Aminah',
    stars: 4,
    text: 'Sepatunya cantik sekali! Sayang boxnya agak penyok sedikit, tapi barangnya aman.',
    date: '3 hari yang lalu',
  },
];
